# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: argocd
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  type: ClusterIP
  ports:
    - name: httpport
      port: 80
      targetPort: 80
